Fix mac build
Adding -Werror broke the mac build, which was passing an incorrect
pointer type:
external/squashfs-tools/squashfs-tools/android.c:52:49: error: incompatible pointer types passing 'mode_t *' (aka 'unsigned short *') to parameter of type 'unsigned int *' [-Werror,-Wincompatible-pointer-types]

fs_config_func takes unsigned int* for its uid, gid, and mode
parameters, but the stat structure contains architecture-specific
types.  Pass pointer to local unsigned int values, and then save
them into the stat structure.

Test: builds on Linux
Change-Id: Ic83c144ffb9c59afe42ab1606d2710e76d19158d